// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: pkg/timetable/pb/timetable.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimetableIntTuple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *TimetableIntTuple) Reset() {
	*x = TimetableIntTuple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimetableIntTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimetableIntTuple) ProtoMessage() {}

func (x *TimetableIntTuple) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimetableIntTuple.ProtoReflect.Descriptor instead.
func (*TimetableIntTuple) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{0}
}

func (x *TimetableIntTuple) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimetableIntTuple) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type TimetableDay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day     string               `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	Timings []*TimetableIntTuple `protobuf:"bytes,2,rep,name=timings,proto3" json:"timings,omitempty"`
}

func (x *TimetableDay) Reset() {
	*x = TimetableDay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimetableDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimetableDay) ProtoMessage() {}

func (x *TimetableDay) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimetableDay.ProtoReflect.Descriptor instead.
func (*TimetableDay) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{1}
}

func (x *TimetableDay) GetDay() string {
	if x != nil {
		return x.Day
	}
	return ""
}

func (x *TimetableDay) GetTimings() []*TimetableIntTuple {
	if x != nil {
		return x.Timings
	}
	return nil
}

type TimetableSchedule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CourseName string          `protobuf:"bytes,1,opt,name=courseName,proto3" json:"courseName,omitempty"`
	Days       []*TimetableDay `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
}

func (x *TimetableSchedule) Reset() {
	*x = TimetableSchedule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimetableSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimetableSchedule) ProtoMessage() {}

func (x *TimetableSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimetableSchedule.ProtoReflect.Descriptor instead.
func (*TimetableSchedule) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{2}
}

func (x *TimetableSchedule) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *TimetableSchedule) GetDays() []*TimetableDay {
	if x != nil {
		return x.Days
	}
	return nil
}

type Timetable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Courses []*TimetableSchedule `protobuf:"bytes,2,rep,name=courses,proto3" json:"courses,omitempty"`
}

func (x *Timetable) Reset() {
	*x = Timetable{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timetable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timetable) ProtoMessage() {}

func (x *Timetable) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timetable.ProtoReflect.Descriptor instead.
func (*Timetable) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{3}
}

func (x *Timetable) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Timetable) GetCourses() []*TimetableSchedule {
	if x != nil {
		return x.Courses
	}
	return nil
}

type GetTimetableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTimetableRequest) Reset() {
	*x = GetTimetableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimetableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableRequest) ProtoMessage() {}

func (x *GetTimetableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableRequest.ProtoReflect.Descriptor instead.
func (*GetTimetableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{4}
}

func (x *GetTimetableRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTimetableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error     string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timetable *Timetable `protobuf:"bytes,3,opt,name=timetable,proto3" json:"timetable,omitempty"`
}

func (x *GetTimetableResponse) Reset() {
	*x = GetTimetableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableResponse) ProtoMessage() {}

func (x *GetTimetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableResponse.ProtoReflect.Descriptor instead.
func (*GetTimetableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{5}
}

func (x *GetTimetableResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetTimetableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTimetableResponse) GetTimetable() *Timetable {
	if x != nil {
		return x.Timetable
	}
	return nil
}

type CreateTimetableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Courses []string `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	UserId  int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *CreateTimetableRequest) Reset() {
	*x = CreateTimetableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimetableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimetableRequest) ProtoMessage() {}

func (x *CreateTimetableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimetableRequest.ProtoReflect.Descriptor instead.
func (*CreateTimetableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTimetableRequest) GetCourses() []string {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *CreateTimetableRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateTimetableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    int64      `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error     string     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timetable *Timetable `protobuf:"bytes,3,opt,name=timetable,proto3" json:"timetable,omitempty"`
}

func (x *CreateTimetableResponse) Reset() {
	*x = CreateTimetableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimetableResponse) ProtoMessage() {}

func (x *CreateTimetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_timetable_pb_timetable_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimetableResponse.ProtoReflect.Descriptor instead.
func (*CreateTimetableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_timetable_pb_timetable_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTimetableResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateTimetableResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateTimetableResponse) GetTimetable() *Timetable {
	if x != nil {
		return x.Timetable
	}
	return nil
}

var File_pkg_timetable_pb_timetable_proto protoreflect.FileDescriptor

var file_pkg_timetable_pb_timetable_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f,
	0x70, 0x62, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x3b, 0x0a,
	0x11, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x54, 0x75, 0x70,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x22, 0x58, 0x0a, 0x0c, 0x54, 0x69,
	0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x61,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x61, 0x79, 0x12, 0x36, 0x0a, 0x07,
	0x74, 0x69, 0x6d, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52, 0x07, 0x74, 0x69, 0x6d,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0x60, 0x0a, 0x11, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x75,
	0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x79,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x79, 0x73, 0x22, 0x53, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73, 0x22, 0x25, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x78, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x4a, 0x0a, 0x16,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x7b, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x32, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x32, 0xc1, 0x01, 0x0a, 0x10, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x1e, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x69, 0x6d,
	0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5a, 0x0a,
	0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x12, 0x21, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x6b, 0x67,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_timetable_pb_timetable_proto_rawDescOnce sync.Once
	file_pkg_timetable_pb_timetable_proto_rawDescData = file_pkg_timetable_pb_timetable_proto_rawDesc
)

func file_pkg_timetable_pb_timetable_proto_rawDescGZIP() []byte {
	file_pkg_timetable_pb_timetable_proto_rawDescOnce.Do(func() {
		file_pkg_timetable_pb_timetable_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_timetable_pb_timetable_proto_rawDescData)
	})
	return file_pkg_timetable_pb_timetable_proto_rawDescData
}

var file_pkg_timetable_pb_timetable_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_timetable_pb_timetable_proto_goTypes = []interface{}{
	(*TimetableIntTuple)(nil),       // 0: timetable.TimetableIntTuple
	(*TimetableDay)(nil),            // 1: timetable.TimetableDay
	(*TimetableSchedule)(nil),       // 2: timetable.TimetableSchedule
	(*Timetable)(nil),               // 3: timetable.Timetable
	(*GetTimetableRequest)(nil),     // 4: timetable.GetTimetableRequest
	(*GetTimetableResponse)(nil),    // 5: timetable.GetTimetableResponse
	(*CreateTimetableRequest)(nil),  // 6: timetable.CreateTimetableRequest
	(*CreateTimetableResponse)(nil), // 7: timetable.CreateTimetableResponse
}
var file_pkg_timetable_pb_timetable_proto_depIdxs = []int32{
	0, // 0: timetable.TimetableDay.timings:type_name -> timetable.TimetableIntTuple
	1, // 1: timetable.TimetableSchedule.days:type_name -> timetable.TimetableDay
	2, // 2: timetable.Timetable.courses:type_name -> timetable.TimetableSchedule
	3, // 3: timetable.GetTimetableResponse.timetable:type_name -> timetable.Timetable
	3, // 4: timetable.CreateTimetableResponse.timetable:type_name -> timetable.Timetable
	4, // 5: timetable.TimetableService.GetTimetable:input_type -> timetable.GetTimetableRequest
	6, // 6: timetable.TimetableService.CreateTimetable:input_type -> timetable.CreateTimetableRequest
	5, // 7: timetable.TimetableService.GetTimetable:output_type -> timetable.GetTimetableResponse
	7, // 8: timetable.TimetableService.CreateTimetable:output_type -> timetable.CreateTimetableResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_timetable_pb_timetable_proto_init() }
func file_pkg_timetable_pb_timetable_proto_init() {
	if File_pkg_timetable_pb_timetable_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_timetable_pb_timetable_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimetableIntTuple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimetableDay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimetableSchedule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timetable); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimetableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimetableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimetableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_timetable_pb_timetable_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimetableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_timetable_pb_timetable_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_timetable_pb_timetable_proto_goTypes,
		DependencyIndexes: file_pkg_timetable_pb_timetable_proto_depIdxs,
		MessageInfos:      file_pkg_timetable_pb_timetable_proto_msgTypes,
	}.Build()
	File_pkg_timetable_pb_timetable_proto = out.File
	file_pkg_timetable_pb_timetable_proto_rawDesc = nil
	file_pkg_timetable_pb_timetable_proto_goTypes = nil
	file_pkg_timetable_pb_timetable_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TimetableServiceClient is the client API for TimetableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimetableServiceClient interface {
	GetTimetable(ctx context.Context, in *GetTimetableRequest, opts ...grpc.CallOption) (*GetTimetableResponse, error)
	CreateTimetable(ctx context.Context, in *CreateTimetableRequest, opts ...grpc.CallOption) (*CreateTimetableResponse, error)
}

type timetableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimetableServiceClient(cc grpc.ClientConnInterface) TimetableServiceClient {
	return &timetableServiceClient{cc}
}

func (c *timetableServiceClient) GetTimetable(ctx context.Context, in *GetTimetableRequest, opts ...grpc.CallOption) (*GetTimetableResponse, error) {
	out := new(GetTimetableResponse)
	err := c.cc.Invoke(ctx, "/timetable.TimetableService/GetTimetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) CreateTimetable(ctx context.Context, in *CreateTimetableRequest, opts ...grpc.CallOption) (*CreateTimetableResponse, error) {
	out := new(CreateTimetableResponse)
	err := c.cc.Invoke(ctx, "/timetable.TimetableService/CreateTimetable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimetableServiceServer is the server API for TimetableService service.
type TimetableServiceServer interface {
	GetTimetable(context.Context, *GetTimetableRequest) (*GetTimetableResponse, error)
	CreateTimetable(context.Context, *CreateTimetableRequest) (*CreateTimetableResponse, error)
}

// UnimplementedTimetableServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTimetableServiceServer struct {
}

func (*UnimplementedTimetableServiceServer) GetTimetable(context.Context, *GetTimetableRequest) (*GetTimetableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimetable not implemented")
}
func (*UnimplementedTimetableServiceServer) CreateTimetable(context.Context, *CreateTimetableRequest) (*CreateTimetableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTimetable not implemented")
}

func RegisterTimetableServiceServer(s *grpc.Server, srv TimetableServiceServer) {
	s.RegisterService(&_TimetableService_serviceDesc, srv)
}

func _TimetableService_GetTimetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).GetTimetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timetable.TimetableService/GetTimetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).GetTimetable(ctx, req.(*GetTimetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_CreateTimetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTimetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).CreateTimetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/timetable.TimetableService/CreateTimetable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).CreateTimetable(ctx, req.(*CreateTimetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TimetableService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "timetable.TimetableService",
	HandlerType: (*TimetableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTimetable",
			Handler:    _TimetableService_GetTimetable_Handler,
		},
		{
			MethodName: "CreateTimetable",
			Handler:    _TimetableService_CreateTimetable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/timetable/pb/timetable.proto",
}
